# Generated by Django 4.2.5 on 2023-09-28 14:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Commune',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commune', models.CharField(max_length=15, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Household',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('commune', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.commune')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=15)),
                ('prenom', models.CharField(max_length=15)),
                ('genre', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=20)),
                ('numero_carte_id', models.CharField(max_length=30, null=True, unique=True)),
                ('lieu_de_delivrance', models.CharField(max_length=30, null=True)),
                ('rue', models.CharField(max_length=30)),
                ('lieu_de_naissance', models.CharField(max_length=50)),
                ('annee_de_naissance', models.DateField()),
                ('nom_du_pere', models.CharField(max_length=30)),
                ('nom_de_la_mere', models.CharField(max_length=30)),
                ('numero_telephone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None)),
                ('relation_avec_chefs_de_menage', models.CharField(choices=[('ENFANTS', 'ENFANTS'), ('MEMBRE_FAMILLE', 'MEMBRE_FAMILLE'), ('AMIS', 'AMIS'), ('GROOM', 'GROOM')], max_length=20)),
                ('photo', models.ImageField(null=True, upload_to='app/photos/')),
                ('est_chef_de_menage', models.BooleanField(default=False)),
                ('est_verifie_par_chef_de_menage', models.BooleanField(default=False)),
                ('est_verifie_par_chef_de_route', models.BooleanField(default=False)),
                ('est_verifie_par_chef_de_quartier', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('commune_de_residence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.commune')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('menage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.household')),
            ],
        ),
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profession', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province', models.CharField(max_length=15, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.person')),
                ('date_arrive', models.DateField(auto_now_add=True)),
                ('date_depart', models.DateField()),
            ],
            bases=('app.person',),
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone', models.CharField(max_length=15, unique=True)),
                ('commune', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.commune')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.province')),
            ],
        ),
        migrations.CreateModel(
            name='Quartier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quartier', models.CharField(max_length=15, unique=True)),
                ('commune', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.commune')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.province')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.zone')),
            ],
        ),
        migrations.AddField(
            model_name='person',
            name='profession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.profession'),
        ),
        migrations.AddField(
            model_name='person',
            name='province_de_residence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.province'),
        ),
        migrations.AddField(
            model_name='person',
            name='quartier_de_residence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.quartier'),
        ),
        migrations.AddField(
            model_name='person',
            name='zone_de_residence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.zone'),
        ),
        migrations.AddField(
            model_name='household',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.province'),
        ),
        migrations.AddField(
            model_name='household',
            name='quartier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.quartier'),
        ),
        migrations.AddField(
            model_name='household',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.zone'),
        ),
        migrations.AddField(
            model_name='commune',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.province'),
        ),
    ]
