# Generated by Django 4.2.5 on 2023-09-28 16:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commune',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.province'),
        ),
        migrations.AlterField(
            model_name='household',
            name='commune',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.commune'),
        ),
        migrations.AlterField(
            model_name='household',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='household',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.province'),
        ),
        migrations.AlterField(
            model_name='household',
            name='quartier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.quartier'),
        ),
        migrations.AlterField(
            model_name='household',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.zone'),
        ),
        migrations.AlterField(
            model_name='person',
            name='commune_de_residence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.commune'),
        ),
        migrations.AlterField(
            model_name='person',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='person',
            name='menage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.household'),
        ),
        migrations.AlterField(
            model_name='person',
            name='numero_telephone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
        migrations.AlterField(
            model_name='person',
            name='profession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.profession'),
        ),
        migrations.AlterField(
            model_name='person',
            name='province_de_residence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.province'),
        ),
        migrations.AlterField(
            model_name='person',
            name='quartier_de_residence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.quartier'),
        ),
        migrations.AlterField(
            model_name='person',
            name='zone_de_residence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.zone'),
        ),
        migrations.AlterField(
            model_name='quartier',
            name='commune',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.commune'),
        ),
        migrations.AlterField(
            model_name='quartier',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.province'),
        ),
        migrations.AlterField(
            model_name='quartier',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.zone'),
        ),
        migrations.AlterField(
            model_name='zone',
            name='commune',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.commune'),
        ),
        migrations.AlterField(
            model_name='zone',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.province'),
        ),
    ]
