# Generated by Django 4.2.5 on 2024-04-28 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_person_est_chef_de_menage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='est_chef_de_menage',
            field=models.IntegerField(choices=[(1, 'Oui'), (0, 'Non')]),
        ),
        migrations.AlterField(
            model_name='person',
            name='est_verifie_par_chef_de_menage',
            field=models.IntegerField(choices=[(1, 'Oui'), (0, 'Non')]),
        ),
        migrations.AlterField(
            model_name='person',
            name='est_verifie_par_chef_de_quartier',
            field=models.IntegerField(choices=[(1, 'Oui'), (0, 'Non')]),
        ),
    ]
