# Generated by Django 4.2.5 on 2023-09-28 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_commune_province_alter_household_commune_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='numero_telephone',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
