# Generated by Django 4.2.5 on 2023-09-22 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.person')),
                ('date_arrive', models.DateField(auto_now_add=True)),
                ('date_depart', models.DateField()),
            ],
            bases=('app.person',),
        ),
    ]
