# Generated by Django 4.2.5 on 2023-09-28 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_person_numero_telephone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='numero_telephone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='app/photos/'),
        ),
    ]
