# Generated by Django 4.2.5 on 2023-10-28 19:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0005_alter_person_est_chef_de_menage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commune',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.province'),
        ),
        migrations.AlterField(
            model_name='household',
            name='commune',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.commune'),
        ),
        migrations.AlterField(
            model_name='household',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='household',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.province'),
        ),
        migrations.AlterField(
            model_name='household',
            name='quartier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.quartier'),
        ),
        migrations.AlterField(
            model_name='household',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.zone'),
        ),
        migrations.AlterField(
            model_name='person',
            name='commune_de_residence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.commune'),
        ),
        migrations.AlterField(
            model_name='person',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='person',
            name='menage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.household'),
        ),
        migrations.AlterField(
            model_name='person',
            name='profession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.profession'),
        ),
        migrations.AlterField(
            model_name='person',
            name='province_de_residence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.province'),
        ),
        migrations.AlterField(
            model_name='person',
            name='quartier_de_residence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.quartier'),
        ),
        migrations.AlterField(
            model_name='person',
            name='relation_avec_chefs_de_menage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.status'),
        ),
        migrations.AlterField(
            model_name='person',
            name='zone_de_residence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.zone'),
        ),
        migrations.AlterField(
            model_name='quartier',
            name='commune',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.commune'),
        ),
        migrations.AlterField(
            model_name='quartier',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.province'),
        ),
        migrations.AlterField(
            model_name='quartier',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.zone'),
        ),
        migrations.AlterField(
            model_name='zone',
            name='commune',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.commune'),
        ),
        migrations.AlterField(
            model_name='zone',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.province'),
        ),
    ]
