# Generated by Django 4.2.5 on 2023-10-30 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_commune_province_alter_household_commune_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zone',
            name='commune',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='communes', to='app.commune'),
        ),
        migrations.AlterField(
            model_name='zone',
            name='province',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='provinces', to='app.province'),
        ),
    ]
