# Generated by Django 4.2.5 on 2024-07-01 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rename_genre_person_gender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='gender',
            new_name='genre',
        ),
    ]
