# Generated by Django 4.2.5 on 2023-11-08 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_quartier_commune_alter_quartier_province_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='date_depart',
            field=models.DateField(),
        ),
    ]
