# Generated by Django 4.2.5 on 2023-11-08 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_person_date_depart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='date_depart',
            field=models.DateField(blank=True, null=True),
        ),
    ]
