# Generated by Django 4.2.5 on 2024-04-04 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='est_chef_de_menage',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='person',
            name='est_verifie_par_chef_de_menage',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='person',
            name='est_verifie_par_chef_de_quartier',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='quartier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.quartier'),
        ),
    ]
